# Generated by Django 2.2.28 on 2026-09-10

import attachment.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAttachmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.IntegerField(default=0)),
                ('image', attachment.fields.ImagePreviewField(blank=True, null=True, upload_to='upload/attachment/source', verbose_name='Изображение')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
            options={
                'verbose_name': 'Изображение с группами',
                'verbose_name_plural': 'Изображения с группами',
                'ordering': ('order_key',),
            },
        ),
        migrations.CreateModel(
            name='CustomImageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='Название группы')),
                ('images', models.ManyToManyField(blank=True, to='custom_attachment.CustomAttachmentImage', verbose_name='Изображения группы')),
            ],
            options={
                'verbose_name': 'Группа изображений',
                'verbose_name_plural': 'Группы изображений',
            },
        ),
        migrations.AddField(
            model_name='customattachmentimage',
            name='image_group',
            field=models.ManyToManyField(blank=True, to='custom_attachment.CustomImageGroup', verbose_name='Группа изображений'),
        ),
    ]
