# Generated by Django 2.2.28 on 2023-10-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Ключевые слова')),
                ('title_length', models.PositiveIntegerField(default=0, verbose_name='max символов заголовка')),
                ('description_length', models.PositiveIntegerField(default=0, verbose_name='max символов описания')),
                ('keywords_length', models.PositiveIntegerField(default=0, verbose_name='max символов ключевые слова')),
                ('autogen', models.BooleanField(default=True, verbose_name='автогенерация текста для новых товаров')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Шаблон контента',
                'verbose_name_plural': 'Шаблоны контента',
            },
        ),
    ]
