# Generated by Django 2.2.28 on 2026-09-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(default=0, verbose_name='')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('type', models.IntegerField(choices=[(0, 'Преимущество компании'), (1, 'Преимущество заказа')], default=0, verbose_name='тип преимущества')),
                ('icon', models.FileField(blank=True, null=True, upload_to='upload/attachment/source', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order_key'],
            },
        ),
    ]
