# Generated by Django 2.2.28 on 2026-09-10 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20211220_1131'),
        ('custom_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(default=0, verbose_name='')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_steps', to='pages.Page', verbose_name='страница')),
            ],
            options={
                'verbose_name': 'Шаг работы',
                'verbose_name_plural': 'Шаги работы',
                'ordering': ['order_key'],
            },
        ),
    ]
