# Generated by Django 2.2.28 on 2026-09-09 11:06

from django.db import migrations, models
import django.db.models.deletion
import investstal.custom_catalog.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime last modified')),
                ('slug', models.SlugField(help_text='The slug will be used to create the page URL, it must be unique among the other pages of the same level.', max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=400, verbose_name='название')),
                ('long_title', models.CharField(blank=True, max_length=400, null=True, verbose_name='длинное название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
            bases=(models.Model, investstal.custom_catalog.models.CatalogMixin),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime last modified')),
                ('slug', models.SlugField(help_text='The slug will be used to create the page URL, it must be unique among the other pages of the same level.', max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=400, verbose_name='название')),
                ('price', models.CharField(blank=True, default='', max_length=255, verbose_name='цена')),
                ('description', models.TextField(blank=True, default='', verbose_name='короткое описание')),
                ('main_content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='основной контент')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('title', models.CharField(max_length=400, verbose_name='название')),
                ('long_title', models.CharField(blank=True, max_length=400, null=True, verbose_name='длинное название')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'корневая страница',
                'verbose_name_plural': 'корневая страница',
            },
            bases=(models.Model, investstal.custom_catalog.models.CatalogMixin),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime last modified')),
                ('slug', models.SlugField(help_text='The slug will be used to create the page URL, it must be unique among the other pages of the same level.', max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=400, verbose_name='название')),
                ('long_title', models.CharField(blank=True, max_length=400, null=True, verbose_name='длинное название')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
            },
            bases=(models.Model, investstal.custom_catalog.models.CatalogMixin),
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'блок металлические двери на главной')], default=0, verbose_name='тип блока')),
                ('order_key', models.PositiveIntegerField(default=0, verbose_name='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_catalog.Category', verbose_name='категория')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_catalog.Section', verbose_name='раздел')),
            ],
            options={
                'verbose_name': 'Элемент каталога на страницах',
                'verbose_name_plural': 'Элементы каталога на страницах',
                'ordering': ['order_key'],
            },
        ),
    ]
