# Generated by Django 2.2.28 on 2026-09-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0002_category_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='square_price',
            field=models.BooleanField(default=False, verbose_name='Цена за 1 кв.м'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='type',
            field=models.IntegerField(choices=[(0, 'блок "металлические двери" на главной'), (1, 'блок "также производим" на главной')], default=0, verbose_name='тип блока'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
    ]
