# Generated by Django 2.2.28 on 2026-09-11 10:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0002_workstep'),
        ('custom_catalog', '0004_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='additional_parameters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'show_in_additional_choices': True}, to='custom_catalog.ParameterValue', verbose_name='дополнительные параметры'),
        ),
        migrations.AddField(
            model_name='category',
            name='advantages',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 1}, to='custom_pages.Advantage', verbose_name='преимущества заказа'),
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.IntegerField(blank=True, choices=[(1, 'По ценовому сегменту'), (2, 'По назначению'), (3, 'По особенностям'), (4, 'По отделке')], null=True, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='category',
            name='main_content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='основной контент'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.CharField(choices=[('new', 'Новинки сверху'), ('asc', 'Дешевле сверху'), ('desc', 'Дороже сверху')], default='new', max_length=10, verbose_name='Сортировать по'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_parameters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'show_in_additional_choices': True}, to='custom_catalog.ParameterValue', verbose_name='дополнительные параметры'),
        ),
        migrations.AddField(
            model_name='product',
            name='advantages',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 1}, to='custom_pages.Advantage', verbose_name='преимущества заказа'),
        ),
        migrations.AddField(
            model_name='product',
            name='long_title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='длинное название'),
        ),
        migrations.AddField(
            model_name='section',
            name='additional_parameters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'show_in_additional_choices': True}, to='custom_catalog.ParameterValue', verbose_name='дополнительные параметры'),
        ),
        migrations.AddField(
            model_name='section',
            name='advantages',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 1}, to='custom_pages.Advantage', verbose_name='преимущества заказа'),
        ),
        migrations.AddField(
            model_name='section',
            name='group',
            field=models.IntegerField(blank=True, choices=[(1, 'По ценовому сегменту'), (2, 'По назначению'), (3, 'По особенностям'), (4, 'По отделке')], null=True, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='section',
            name='main_content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='основной контент'),
        ),
        migrations.AddField(
            model_name='section',
            name='sort',
            field=models.CharField(choices=[('new', 'Новинки сверху'), ('asc', 'Дешевле сверху'), ('desc', 'Дороже сверху')], default='new', max_length=10, verbose_name='Сортировать по'),
        ),
    ]
