# Generated by Django 2.2.28 on 2026-09-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0006_daltot_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='advantages',
        ),
        migrations.RemoveField(
            model_name='product',
            name='advantages',
        ),
        migrations.RemoveField(
            model_name='section',
            name='advantages',
        ),
        migrations.AddField(
            model_name='category',
            name='price_description',
            field=models.TextField(blank=True, help_text='текст возле цены на странице товара', null=True, verbose_name='описание цены'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_description',
            field=models.TextField(blank=True, help_text='текст возле цены на странице товара', null=True, verbose_name='описание цены'),
        ),
        migrations.AddField(
            model_name='section',
            name='price_description',
            field=models.TextField(blank=True, help_text='текст возле цены на странице товара', null=True, verbose_name='описание цены'),
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.IntegerField(blank=True, choices=[(1, 'Двери по наружной отделке'), (2, 'Двери по месту установки'), (3, 'Двери по особенностям'), (4, 'Металлоконструкции')], null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort',
            field=models.TextField(choices=[('new', 'Новинки сверху'), ('asc', 'Дешевле сверху'), ('desc', 'Дороже сверху')], default='new', verbose_name='Сортировать по'),
        ),
        migrations.AlterField(
            model_name='parametergroup',
            name='group_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Стандартная конструкция'), (2, 'Фурнитура'), (3, 'Габариты'), (4, 'Доставка дверей'), (5, 'Установка дверей'), (6, 'Отделки')], help_text='Используется на странице товара для деления в характеристиках', null=True, verbose_name='Тип параметра'),
        ),
        migrations.AlterField(
            model_name='section',
            name='group',
            field=models.IntegerField(blank=True, choices=[(1, 'Двери по наружной отделке'), (2, 'Двери по месту установки'), (3, 'Двери по особенностям'), (4, 'Металлоконструкции')], null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sort',
            field=models.TextField(choices=[('new', 'Новинки сверху'), ('asc', 'Дешевле сверху'), ('desc', 'Дороже сверху')], default='new', verbose_name='Сортировать по'),
        ),
    ]
