# Generated by Django 2.2.28 on 2026-09-16 05:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0008_section_category_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='root',
            name='main_content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='основной контент'),
        ),
    ]
